In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import glob
import os
from math import log

In [2]:
allFiles = sorted(glob.glob("*.txt"),key=os.path.getmtime) # includes all files into a single stucture,
# Sorted by modification time so that the first measurement is first...
print(allFiles)

['SHG_Signal_280Deg_07132017.txt', 'SHG_Background_280Deg_07132017.txt', 'SHG_Background_275Deg_07132017.txt', 'SHG_Signal_275Deg_07132017.txt', 'SHG_Signal_270Deg_07132017.txt', 'SHG_Background_270Deg_07132017.txt', 'SHG_Background_265Deg_07132017.txt', 'SHG_Signal_265Deg_07132017.txt', 'SHG_Signal_260Deg_07132017.txt', 'SHG_Background_260Deg_07132017.txt', 'SHG_Background_255Deg_07132017.txt', 'SHG_Signal_255Deg_07132017.txt', 'SHG_Signal_250Deg_07132017.txt', 'SHG_Background_250Deg_07132017.txt', 'SHG2_Signal_280Deg_07132017.txt', 'SHG2_Background_280Deg_07132017.txt', 'SHG2_Background_275Deg_07132017.txt', 'SHG2_Signal_275Deg_07132017.txt', 'SHG2_Signal_270Deg_07132017.txt', 'SHG2_Background_270Deg_07132017.txt', 'SHG2_Background_265Deg_07132017.txt', 'SHG2_Signal_265Deg_07132017.txt', 'SHG2_Signal_260Deg_07132017.txt', 'SHG2_Background_260Deg_07132017.txt', 'SHG2_Background_255Deg_07132017.txt', 'SHG2_Signal_255Deg_07132017.txt', 'SHG2_Signal_250Deg_07132017.txt', 'SHG2_Background

In [3]:
frame = pd.DataFrame()
df = pd.DataFrame()

In [4]:
for i,file_ in enumerate(allFiles):
#    f = open(file_,'r')
#     for j,line in enumerate(f):
#         if j == 1:
#             date = line[14:22]
#             break
    df = pd.read_csv(file_,index_col = None, header=None, skiprows = 10, skipfooter = 1, delimiter = '\t')
#     frame[file_] = df[5]
    df['file']=file_
    df['timeDelay']= df[1]
    df['PDvalue'] = df[3]
#     df['date']=date
    if i < 1:
        frame = df
    else:
        frame = frame.append(df)

/Users/sanjaykhatri/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:7: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skip_footer; you can avoid this warning by specifying engine='python'.


In [5]:
times = pd.Series()
PDvalues = pd.Series()
AvgPD50 = pd.Series()
itr = 0.000125
offset = 0.023
for i in range(0,100):
    time = frame[1][i]
    PDvalue = frame[3][i]
    times = times.append(time)
    PDvalues = PDvalues.append(PDvalue)
#print(len(PDvalues))
PDvalues = PDvalues.values.reshape(100,len(allFiles))
Background = np.array([PDvalues[:,1],PDvalues[:,2],PDvalues[:,5],PDvalues[:,6],PDvalues[:,9],PDvalues[:,10],PDvalues[:,13],\
                       PDvalues[:,15],PDvalues[:,16],PDvalues[:,19],PDvalues[:,20],PDvalues[:,23],PDvalues[:,24],PDvalues[:,27],\
                       PDvalues[:,29],PDvalues[:,30],PDvalues[:,32],PDvalues[:,35],PDvalues[:,36],PDvalues[:,39],PDvalues[:,40],\
                       PDvalues[:,43],PDvalues[:,44],PDvalues[:,47],PDvalues[:,48],PDvalues[:,51],PDvalues[:,52],PDvalues[:,55],\
                      PDvalues[:,57],PDvalues[:,58],PDvalues[:,61],PDvalues[:,62],PDvalues[:,65],PDvalues[:,66],PDvalues[:,69],\
                      PDvalues[:,71],PDvalues[:,72],PDvalues[:,75],PDvalues[:,76],PDvalues[:,79],PDvalues[:,80],PDvalues[:,83],\
                      PDvalues[:,85],PDvalues[:,86],PDvalues[:,89],PDvalues[:,90],PDvalues[:,93],PDvalues[:,94],PDvalues[:,97],\
                      PDvalues[:,99],PDvalues[:,100],PDvalues[:,103],PDvalues[:,104],PDvalues[:,107],PDvalues[:,108],PDvalues[:,111],\
                      PDvalues[:,113],PDvalues[:,114],PDvalues[:,117],PDvalues[:,118],PDvalues[:,121],PDvalues[:,122],PDvalues[:,125],\
                      PDvalues[:,127],PDvalues[:,128],PDvalues[:,131],PDvalues[:,132],PDvalues[:,135],PDvalues[:,136],PDvalues[:,139]])
Background_mean = np.mean(Background, axis = 1)
PMT_Raw = np.array([PDvalues[:,0],PDvalues[:,3],PDvalues[:,4],PDvalues[:,7],PDvalues[:,8],PDvalues[:,11],PDvalues[:,12],\
                    PDvalues[:,14],PDvalues[:,17],PDvalues[:,18],PDvalues[:,21],PDvalues[:,22],PDvalues[:,25],PDvalues[:,26],\
                    PDvalues[:,28],PDvalues[:,31],PDvalues[:,33],PDvalues[:,34],PDvalues[:,37],PDvalues[:,38],PDvalues[:,41],\
                    PDvalues[:,42],PDvalues[:,45],PDvalues[:,46],PDvalues[:,49],PDvalues[:,50],PDvalues[:,53],PDvalues[:,54],\
                   PDvalues[:,56],PDvalues[:,59],PDvalues[:,60],PDvalues[:,63],PDvalues[:,64],PDvalues[:,67],PDvalues[:,68],\
                   PDvalues[:,70],PDvalues[:,73],PDvalues[:,74],PDvalues[:,77],PDvalues[:,78],PDvalues[:,81],PDvalues[:,82],\
                   PDvalues[:,84],PDvalues[:,87],PDvalues[:,88],PDvalues[:,91],PDvalues[:,92],PDvalues[:,95],PDvalues[:,96],\
                   PDvalues[:,98],PDvalues[:,101],PDvalues[:,102],PDvalues[:,105],PDvalues[:,106],PDvalues[:,109],PDvalues[:,110],\
                   PDvalues[:,112],PDvalues[:,115],PDvalues[:,116],PDvalues[:,119],PDvalues[:,120],PDvalues[:,123],PDvalues[:,124],\
                   PDvalues[:,126],PDvalues[:,129],PDvalues[:,130],PDvalues[:,133],PDvalues[:,134],PDvalues[:,137],PDvalues[:,138]])
MeanPMT1 = np.mean(PMT_Raw,axis = 1)

PMT_Net = MeanPMT1 - Background_mean
MeanNET = np.reshape(PMT_Net,(10,7)) # As you add more files, change the 4 to the number of runs. 7 is b/c I took 7 different angles
MeanNET2 = np.mean(MeanNET,axis =0)
THzEnergy = np.array([480,450,390,310,235,160,105])
PMT_STD = np.std(MeanNET,axis = 0)
PMT_Err = PMT_STD/(10**0.5)
w = (PMT_Err/(MeanNET2*log(10)))**-2

#print(Background_mean)
print(MeanNET)
#print(PMT_)
#print(MeanNET2)
LogPMT = np.log10(np.absolute(MeanNET2))
LogTHz = np.log10(np.absolute(THzEnergy))





[[-0.063945 -0.054555 -0.052355 -0.033251 -0.039358 -0.02784  -0.026865]
 [-0.052848 -0.063574 -0.055807 -0.036681 -0.032956 -0.023763 -0.012991]
 [-0.064939 -0.063763 -0.049452 -0.049771 -0.038677 -0.03578  -0.028221]
 [-0.04985  -0.049497 -0.039427 -0.039165 -0.026885 -0.018814 -0.012178]
 [-0.056613 -0.063608 -0.057473 -0.045734 -0.035489 -0.027128 -0.022929]
 [-0.071757 -0.050342 -0.040402 -0.031437 -0.024887 -0.032118 -0.014436]
 [-0.05185  -0.053518 -0.046282 -0.048834 -0.033823 -0.024036 -0.01499 ]
 [-0.045963 -0.052343 -0.050053 -0.037357 -0.018978 -0.02233  -0.023553]
 [-0.054342 -0.041988 -0.042481 -0.028017 -0.026556 -0.030892 -0.023007]
 [-0.046714 -0.047452 -0.03812  -0.038902 -0.022813 -0.021275 -0.023303]]


In [6]:
Delta = sum(w)*sum(w*LogTHz**2) - (sum(w*LogTHz))**2
A = (sum(w*LogTHz**2)*sum(w*LogPMT) - sum(w*LogTHz)*sum(w*LogTHz*LogPMT))/Delta
B = (sum(w)*sum(w*LogTHz*LogPMT) - (sum(w*LogPMT)*sum(w*LogTHz)))/Delta
# Least Squares Fitting Parameters above
print(w)
print(A)
print(B)
err = (((len(LogPMT)-2)**-1) * sum((LogPMT - A -B*LogTHz)**2)**0.5)
errorA = (sum(w*LogTHz**2)/Delta)**0.5
errorB = (sum(w)/Delta)**0.5
print(errorA)
print(errorB)

[ 2561.98786764  3078.71925785  2735.10038789  1683.28249956  1094.56825663
  1441.03072697   675.79806686]
-3.1309051442
0.698005930014
0.116288096997
0.0459979517402


In [111]:
plt.plot(LogTHz, A + B*LogTHz,'r',label = 'Fit: y=0.70x -3.13')
plt.plot(LogTHz, LogPMT,'b.', label = 'Data')
plt.grid(True)
plt.xlabel('Log(THz Energy)')
plt.ylabel('Log(PMT Signal)')
plt.legend(loc = 'upper left')
plt.show()
#plt.savefig('PMT_SignalVsTHzEnergy_07132017.png')