In [20]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import glob
import os
from math import log

In [21]:
allFiles = sorted(glob.glob("*.txt"),key=os.path.getmtime) # includes all files into a single stucture,
# Sorted by modification time so that the first measurement is first...
print(allFiles)

['PMT_Signal_120mW_071717.txt', 'PMT_Background_120mW_071717.txt', 'PMT_Background_110mW_071717.txt', 'PMT_Signal_110mW_071717.txt', 'PMT_Signal_100mW_071717.txt', 'PMT_Background_100mW_071717.txt', 'PMT_Background_90mW_071717.txt', 'PMT_Signal_90mW_071717.txt', 'PMT_Signal_80mW_071717.txt', 'PMT_Background_80mW_071717.txt', 'PMT2_Signal_120mW_071717.txt', 'PMT2_Background_120mW_071717.txt', 'PMT2_Background_110mW_071717.txt', 'PMT2_Signal_110mW_071717.txt', 'PMT2_Signal_100mW_071717.txt', 'PMT2_Background_100mW_071717.txt', 'PMT2_Background_90mW_071717.txt', 'PMT2_Signal_90mW_071717.txt', 'PMT2_Signal_80mW_071717.txt', 'PMT2_Background_80mW_071717.txt', 'PMT4_Signal_120mW_071717.txt', 'PMT4_Background_120mW_071717.txt', 'PMT4_Background_110mW_071717.txt', 'PMT4_Signal_110mW_071717.txt', 'PMT4_Signal_100mW_071717.txt', 'PMT4_Background_100mW_071717.txt', 'PMT4_Background_90mW_071717.txt', 'PMT4_Signal_90mW_071717.txt', 'PMT4_Signal_80mW_071717.txt', 'PMT4_Background_80mW_071717.txt', '

In [22]:
frame = pd.DataFrame()
df = pd.DataFrame()

In [23]:
for i,file_ in enumerate(allFiles):
#    f = open(file_,'r')
#     for j,line in enumerate(f):
#         if j == 1:
#             date = line[14:22]
#             break
    df = pd.read_csv(file_,index_col = None, header=None, skiprows = 10, skipfooter = 1, delimiter = '\t')
#     frame[file_] = df[5]
    df['file']=file_
    df['timeDelay']= df[1]
    df['PDvalue'] = df[3]
#     df['date']=date
    if i < 1:
        frame = df
    else:
        frame = frame.append(df)

/Users/sanjaykhatri/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:7: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skip_footer; you can avoid this warning by specifying engine='python'.


In [28]:
times = pd.Series()
PDvalues = pd.Series()
AvgPD50 = pd.Series()
itr = 0.000125
offset = 0.023
for i in range(0,100):
    time = frame[1][i]
    PDvalue = frame[3][i]
    times = times.append(time)
    PDvalues = PDvalues.append(PDvalue)
#print(len(PDvalues))
PDvalues = PDvalues.values.reshape(100,len(allFiles))
Background = np.array([PDvalues[:,1],PDvalues[:,2],PDvalues[:,5],PDvalues[:,6],PDvalues[:,9],\
                       PDvalues[:,11],PDvalues[:,12],PDvalues[:,15],PDvalues[:,16],PDvalues[:,19],\
                       PDvalues[:,21],PDvalues[:,22],PDvalues[:,25],PDvalues[:,26],PDvalues[:,29],\
                       PDvalues[:,31],PDvalues[:,32],PDvalues[:,35],PDvalues[:,36],PDvalues[:,39],\
                       PDvalues[:,41],PDvalues[:,42],PDvalues[:,45],PDvalues[:,46],PDvalues[:,49],\
                       PDvalues[:,51],PDvalues[:,52],PDvalues[:,55],PDvalues[:,56],PDvalues[:,59],\
                       PDvalues[:,61],PDvalues[:,62],PDvalues[:,65],PDvalues[:,66],PDvalues[:,69],\
                       PDvalues[:,71],PDvalues[:,72],PDvalues[:,75],PDvalues[:,76],PDvalues[:,79]])
                       #PDvalues[:,81],PDvalues[:,82],PDvalues[:,85],PDvalues[:,86],PDvalues[:,89]])
                       #PDvalues[:,91],PDvalues[:,92],PDvalues[:,95],PDvalues[:,96],PDvalues[:,99]])
Background_mean = np.mean(Background, axis = 1)
PMT_Raw = np.array([PDvalues[:,0],PDvalues[:,3],PDvalues[:,4],PDvalues[:,7],PDvalues[:,8],\
                    PDvalues[:,10],PDvalues[:,13],PDvalues[:,14],PDvalues[:,17],PDvalues[:,18],\
                    PDvalues[:,20],PDvalues[:,23],PDvalues[:,24],PDvalues[:,27],PDvalues[:,28],\
                    PDvalues[:,30],PDvalues[:,33],PDvalues[:,34],PDvalues[:,37],PDvalues[:,38],\
                    PDvalues[:,40],PDvalues[:,43],PDvalues[:,44],PDvalues[:,47],PDvalues[:,48],\
                    PDvalues[:,50],PDvalues[:,53],PDvalues[:,54],PDvalues[:,57],PDvalues[:,58],\
                    PDvalues[:,60],PDvalues[:,63],PDvalues[:,64],PDvalues[:,67],PDvalues[:,68],\
                    PDvalues[:,70],PDvalues[:,73],PDvalues[:,74],PDvalues[:,77],PDvalues[:,78]])
                    #PDvalues[:,80],PDvalues[:,83],PDvalues[:,84],PDvalues[:,87],PDvalues[:,88]])
                    #PDvalues[:,90],PDvalues[:,93],PDvalues[:,94],PDvalues[:,97],PDvalues[:,98]])
MeanPMT1 = np.mean(PMT_Raw,axis = 1)

PMT_Net = MeanPMT1 - Background_mean
MeanNET = np.reshape(PMT_Net,(8,5)) # As you add more files, change the 4 to the number of runs. 7 is b/c I took 7 different angles
MeanNET2 = np.mean(MeanNET,axis =0)
THzEnergy = np.array([120,110,100,90,80])
PMT_STD = np.std(MeanNET,axis = 0)
PMT_Err = PMT_STD/(8**0.5)
w = (PMT_Err/(MeanNET2*log(10)))**-2

print(Background_mean)
print(MeanPMT1)
print(MeanNET)
#print(PMT_)
#print(MeanNET2)
LogPMT = np.log10(np.absolute(MeanNET2))
LogTHz = np.log10(np.absolute(THzEnergy))
print(LogPMT)

[-0.195411 -0.160279 -0.138781 -0.124037 -0.104475 -0.192259 -0.167829
 -0.138292 -0.113745 -0.096721 -0.174153 -0.146955 -0.128062 -0.115334
 -0.095628 -0.184778 -0.15803  -0.133943 -0.109661 -0.09987  -0.190363
 -0.172119 -0.138881 -0.119636 -0.099045 -0.191127 -0.161    -0.14356
 -0.116366 -0.099074 -0.184192 -0.16066  -0.135906 -0.116536 -0.100905
 -0.183651 -0.149291 -0.140936 -0.120705 -0.099608]
[-0.231025 -0.193389 -0.157616 -0.132531 -0.120689 -0.222283 -0.188479
 -0.162107 -0.130944 -0.114552 -0.210904 -0.175603 -0.148455 -0.124255
 -0.110209 -0.215408 -0.18726  -0.156067 -0.13179  -0.119601 -0.239767
 -0.195172 -0.160953 -0.14544  -0.111934 -0.219571 -0.188375 -0.168904
 -0.129682 -0.112376 -0.230762 -0.195003 -0.158665 -0.141952 -0.112239
 -0.212136 -0.181481 -0.166482 -0.131414 -0.119347]
[[-0.035614 -0.03311  -0.018835 -0.008494 -0.016214]
 [-0.030024 -0.02065  -0.023815 -0.017199 -0.017831]
 [-0.036751 -0.028648 -0.020393 -0.008921 -0.014581]
 [-0.03063  -0.02923  -0.022

In [29]:
Delta = sum(w)*sum(w*LogTHz**2) - (sum(w*LogTHz))**2
A = (sum(w*LogTHz**2)*sum(w*LogPMT) - sum(w*LogTHz)*sum(w*LogTHz*LogPMT))/Delta
B = (sum(w)*sum(w*LogTHz*LogPMT) - (sum(w*LogPMT)*sum(w*LogTHz)))/Delta
# Least Squares Fitting Parameters above
print(w)
print(A)
print(B)
err = (((len(LogPMT)-2)**-1) * sum((LogPMT - A -B*LogTHz)**2)**0.5)
errorA = (sum(w*LogTHz**2)/Delta)**0.5
errorB = (sum(w)/Delta)**0.5
print(errorA)
print(errorB)

[  922.82958025  1709.46158407  4655.89415589   254.1336421   1172.89500012]
-5.69135198404
2.0285255988
0.445345912064
0.222372055722


In [32]:
plt.plot(LogTHz, A + B*LogTHz,'r',label = 'Fit: y=2.02x -2.47')
plt.plot(LogTHz, LogPMT,'b.', label = 'Data')
plt.grid(True)
plt.xlabel('Log(Laser Power)')
plt.ylabel('Log(PMT Signal)')
plt.legend(loc = 'upper left')
#plt.show()
plt.savefig('LogPMT_Vs_LogLaser_07172017.png')